# Generated by Django 6.0.2 on 2026-03-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldrate',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
        migrations.AddField(
            model_name='goldrate',
            name='making_charge_per_gram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
