# Generated by Django 6.0.2 on 2026-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_goldrate_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldrate',
            name='making_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Per Gram')], default='percent', max_length=10),
        ),
    ]
