# Generated by Django 6.0.2 on 2026-02-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
