# Generated by Django 6.0.2 on 2026-03-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopify_product_id',
            field=models.CharField(max_length=255),
        ),
    ]
