# Generated by Django 6.0.2 on 2026-03-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_variant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='charge_tax',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_tracked',
            field=models.BooleanField(default=True),
        ),
    ]
