# Generated by Django 6.0.2 on 2026-03-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_shopify_variant_id_alter_product_charge_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
